# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Docs
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/docs" # the subpath of your site, e.g. /blog
url: "https://fokkezb.github.io" # the base hostname & protocol for your site
repository: fokkezb/docs

# Build settings
markdown: kramdown
exclude: [ bower.json, Gemfile, Gemfile.lock, README.md ]

# Use GitHub.io overrides local as well
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax