# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: The Things Network
email: wienke@thethingsnetwork.org
description: > # this means to ignore newlines until "baseurl:"
  We are building a global open free crowdsourced long range low battery IoT
  data network.
baseurl: "/docs" # the subpath of your site, e.g. /blog
url: "https://fokkezb.github.io" # the base hostname & protocol for your site
repository: fokkezb/docs

# Build settings
markdown: kramdown
exclude: [ node_modules, Gemfile, Gemfile.lock, package.json, README.md, webpack.config.js ]
gems:
  - jemoji

# Use GitHub.io overrides local as well
lsi: false
safe: true
source: .
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax